### ISSUE TITLE
API key not working 

### ISSUE THREAD

**Issue by jackocyber** [stephenholzman/chartsoncharts-tutorials#1]
I have a register api key, however, when I try to run the code it gives me this error: 

stop(sprintf("Open FEC API request failed [%s]\n%s\n<%s>", status_code(resp), resp$response), call. = FALSE)

I am running your code here with a different api key, but it does not work. Any help would be appreciated!

**Comment by stephenholzman** [comment]
I've created a package that makes working with the API easier, more info can be found at https://github.com/stephenholzman/tidyusafec

Hopefully this helps!
